spring:
  datasource:
    username: hkoo
    password: hkoo
    url: jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&characterSetResults=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081